### ISSUE TITLE
运行run_win 报错

### ISSUE THREAD

**Issue by ErPurE** [neoedmund/dota2_dragon_chess_ai_autoplay#1]
运行报错：
E:\Tools\dota2_dragon_chess_ai_autoplay\app>jdk-21.0.3\bin\java --add-opens=java.base\java.nio=ALL-UNNAMED --add-opens=java.base\java.util=ALL-UNNAMED -cp dota2chessai.jar neoe.textfrog.Main run1.tfg
Error occurred during initialization of boot layer
java.lang.RuntimeException: Unable to parse --add-opens <module>/<package>: java.base\java.nio
![image](https://github.com/user-attachments/assets/9ae715f3-d9a5-40b2-8978-448e8f1bce3c)

**Comment by neoedmund** [comment]
打包打错了， 先把 '--add-opens=java.base\java.nio=ALL-UNNAMED --add-opens=java.base\java.util=ALL-UNNAMED'
\ 替换 成 /
'--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'
一会儿重发一个包

**Comment by neoedmund** [comment]
请再试一下 release v1.1.1
