### ISSUE TITLE
识别错误

### ISSUE THREAD

**Issue by nousername2050** [neoedmund/dota2_dragon_chess_ai_autoplay#2]
依然用不了， 屏幕15.6寸1920分辨率125%缩放，程序和游戏都按步骤来了，jar那个东西依然缩到右边屏幕外面，cmd那个识别宝石全身错误的
![Uploading 屏幕截图 2024-07-17 205912.png…]()

**Comment by nousername2050** [comment]
![Uploading 屏幕截图 2024-07-17 205912.png…]()

**Comment by neoedmund** [comment]
缩放只能100%

**Comment by nousername2050** [comment]
![Uploading 屏幕截图 2024-07-17 205912.jpg…]()

**Comment by nousername2050** [comment]
然后我也试过把屏幕缩放改为100，但是jar那个东西依旧飞到右边屏幕外面了，识别不了dota，cmd算不出优解然后停住了

**Comment by neoedmund** [comment]
你需要重新下载最新zip

**Comment by nousername2050** [comment]
我下的就是1.2

**Comment by neoedmund** [comment]
看不到截图

**Comment by nousername2050** [comment]
我就是b站发不了图就来这边，结果这边也发不出图

**Comment by nousername2050** [comment]
能个邮箱或者我用网盘分享？

**Comment by nousername2050** [comment]
![333](https://github.com/user-attachments/assets/5de5fe25-b2b5-46ad-8d3c-b89fede0715f)
![屏幕截图 2024-07-17 205912](https://github.com/user-attachments/assets/ab959730-a909-4b73-8e6f-c91e9d63bc35)
![屏幕截图 2024-07-18 012252](https://github.com/user-attachments/assets/aef3adf3-315a-4f9d-a021-82f341d99d6a)

**Comment by qpcheese** [comment]
@nousername2050 

Works like a charm, make sure that the pink  crosshair is lined up exactly as in the picture below, adjut it by moving the dota 2 window.
If its aligned correctly then the AI works, it got me 57k score.
![Screenshot_20240717_210746](https://github.com/user-attachments/assets/c3ca71da-1aa9-4512-a233-5dd93f4fea80)

**Comment by nousername2050** [comment]
我见不到瞄准框，i cant find that pink crosshair so the ai fail to match icon.

**Comment by qpcheese** [comment]
> 我见不到瞄准框，i cant find that pink crosshair so the ai fail to match icon.

try 1920x1080p monitor 16:9  , 1600x900 in dota , your monitor resolution has to match or the script wont know what is what , even if aspect ratio wrong.
Crosshair window maybe appear behind dota because your monitor is small, dont have 1080p resolution

**Comment by neoedmund** [comment]
1。没有瞄准框,重新下最新版
2。你是不是开了桌面缩放了。

**Comment by qpcheese** [comment]
> 1。没有瞄准框,重新下最新版 2。你是不是开了桌面缩放了。

i downloaded v 1.2 , two hours ago, i get pink aim  window still.
You must have failed with commit if its not suppose to be there..

![kPrLPsFR9s](https://github.com/user-attachments/assets/83f9385f-1f79-4144-85a9-d2015d56f9e3)

**Comment by neoedmund** [comment]
> > 1。没有瞄准框,重新下最新版 2。你是不是开了桌面缩放了。
> 
> i downloaded v 1.2 , two hours ago, i get pink aim window still. You must have failed with commit if its not suppose to be there..
>
You are okay.  There is pink cross.
I said to @nousername2050

**Comment by nousername2050** [comment]
成了，太强了，那些连招我根本反应不过来啦，去b站给你三连了
