### ISSUE TITLE
Screen support

### ISSUE THREAD

**Issue by codedpro** [neoedmund/dota2_dragon_chess_ai_autoplay#4]
all screen dosen't support that resolution that you set,
could you please make it lower like 1280 ?

**Comment by neoedmund** [comment]
Not about screen size, just need adjust dota2 window size.

**Comment by codedpro** [comment]
it dosen't work -w 1600 -h 900 -windowed i set this but not working

**Comment by codedpro** [comment]
your app doesn't open when dota2 is not in that resolution and size of 1600,
when I change Ur app's setting to accept lower screens of dota2,
it will be open and i will adjust its position on game, like in 800 resolution it will fit there but it wont work,
also I couldn't figure it out how can i set that resolution when my screen support up to 1366, nor the launch options or in game console i can't change the resolution and window size of my game , so could you please check this out?

**Comment by neoedmund** [comment]
check all the point:
1. magenta-cross is just like the picture
2. dota2 render quality is  max
3. desktop scaling is 100%

maybe some screenshot will help.

**Comment by codedpro** [comment]
![image](https://github.com/user-attachments/assets/40aa8282-ae02-40ae-89e7-6b3298114d4c)
![image](https://github.com/user-attachments/assets/7de2c5fb-ca4b-4979-9ecf-b191247db5b1)
![image](https://github.com/user-attachments/assets/370ba5f5-c987-4ef1-be1e-513ab59a2bcd)

**Comment by codedpro** [comment]
in last screen shot as you see when its 800 your app will be opened ,
else if its 1600 it wont open at all

![image](https://github.com/user-attachments/assets/dbaa0b13-66ed-4176-8ec3-9ec54a5e8f18)
![image](https://github.com/user-attachments/assets/14773016-4a87-4f49-a145-3d1578b55936)

**Comment by neoedmund** [comment]
wow, I see the 1600x900 is not available in the dota client. could you try render API other than DX11 like Vulkan to see if 1600x900 is available ?

**Comment by neoedmund** [comment]
Oh your screen is 1366x768 so you need to make it exceeds 1600 else the AI won't work at this time!

**Comment by codedpro** [comment]
> wow, I see the 1600x900 is not available in the dota client. could you try render API other than DX11 like Vulkan to see if 1600x900 is available ?

still dont have option,
also as i was saying can u change the ai to work on other screens too

**Comment by neoedmund** [comment]
could you try
```
	T . w = 61
	T . h = 61
```
?

**Comment by codedpro** [comment]
> could you try
> 
> ```
> 	T . w = 61
> 	T . h = 61
> ```
> 
> ?

![image](https://github.com/user-attachments/assets/494f5012-59e7-400d-bfb2-0c227a834785)
![image](https://github.com/user-attachments/assets/df8ef941-c6ec-4b23-be5f-0edee29813f3)


didnt work

**Comment by neoedmund** [comment]
[jar1.zip](https://github.com/user-attachments/files/16317579/jar1.zip)
please replace the jar file with the one in zip and
add `T . w0 = 48 ` also magenta-cross need to be set a little left-top-wards.

**Comment by codedpro** [comment]
![image](https://github.com/user-attachments/assets/78c4ba38-9b71-4220-b69d-da8990573464)
![image](https://github.com/user-attachments/assets/41669f22-7cd3-40e4-8ff1-4fedfc80d56d)
![image](https://github.com/user-attachments/assets/5eeac49a-4e56-4e68-afa2-f0f5dd852342)

here is the result didnt work,

**Comment by neoedmund** [comment]
use 1280x720 please

**Comment by codedpro** [comment]
![image](https://github.com/user-attachments/assets/2c77653c-0976-4bd9-9e6c-3d5cd69ce41b)
![image](https://github.com/user-attachments/assets/81db5a4e-35b2-4fdf-9fc5-692273fda529)
![image](https://github.com/user-attachments/assets/2c634145-a2d6-4e40-9ca6-e019223d8be3)

its amazing it worked!

bot is so smooth and won it perfectly Nice One ,
Thanks a Lot <3
