### ISSUE TITLE
你好！脚本策略问题

### ISSUE THREAD

**Issue by Juggernautsst** [neoedmund/dota2_dragon_chess_ai_autoplay#6]
请问该脚本采用的是什么样的策略？我的想法是贪心法可能效率就已经非常高。另外在windows系统上的适配不是很好，主要问题在于如果不将鼠标移动到cmd上cmd将不会执行。请问可以贴出源码以供参考吗？

**Comment by neoedmund** [comment]
向前看4步的搜索算法。
4步以内评分最高的走法。单步贪心可能不太漂亮，比如5333,不如3555。
由于对这个游戏表现已经很好，没有太多别的优化。
一般学了搜索算法的书都能写出来，代码暂时不公开了。
本来只针对自己的环境做的小程序，通关了就完成任务了。大家想要就修改一下共享了，我Windows上根本没安装Dota2。
